import type { Metadata } from "next";
import Footer from "@/components/Footer";
import "@styles/GlobalStyles.scss";
import { Zen_Kaku_Gothic_New } from "next/font/google";

const zenKaku = Zen_Kaku_Gothic_New({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "ステディxスタディ",
    description: "Generated by create next app",

    icons: {
        icon: "images/icon.svg",
        apple: "images/icon.svg",
    },
    appleWebApp: {
        capable: true,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={zenKaku.className}>
                {children}
                <Footer />
            </body>
        </html>
    );
}
